export const restaurantMenu = [
  {
    id: "m1",
    title: "Western Burger",
    description: "Has onion rings and BBQ sauce",
    price: 4.99,
    calories: 599,
    category: "burgers",
    image: "/burger1.webp",
    quantity: 0,
  },
  {
    id: "m2",
    title: "Avocado Burger",
    description: "Has avocado and bacon",
    price: 8.99,
    calories: 599,
    category: "burgers",
    image: "burger2.webp",
    quantity: 0,
  },

  {
    id: "m3",
    title: "Egg Burger",
    description: "Fried egg and bacon",
    price: 6.99,
    calories: 599,
    category: "burgers",
    image: "burger3.webp",
    quantity: 0,
  },
  {
    id: "m7",
    title: "Classic Burger",
    description: "Our classic burger",
    price: 1.99,
    calories: 250,
    category: "burgers",
    image: "/burger4.webp",
    quantity: 0,
  },
  {
    id: "m4",
    title: "Fries",
    description: "Handcut fresh every day!",
    price: 3.99,
    calories: 400,
    category: "fries",
    image: "fries1.webp",
    quantity: 0,
  },
  {
    id: "m5",
    title: "Sweet Potato Fries",
    description: "Handcut fresh every day. Served with cinnamon butter.",
    price: 3.99,
    calories: 300,
    category: "fries",
    image: "fries2.webp",
    quantity: 0,
  },
  {
    id: "m6",
    title: "Fountain Drink",
    description: "soda",
    price: 1.99,
    calories: 250,
    category: "drinks",
    image: "soda1.webp",
    quantity: 0,
  },
];
