export const restaurantMenu = [
  {
    id: "m1",
    name: "Western Burger",
    description: "Has onion rings and BBQ sauce",
    price: 4.99,
    calories: 599,
    category: "burgers",
    image: "/burger1.webp",
  },
  {
    id: "m2",
    name: "Avocado Burger",
    description: "Has avocado and bacon",
    price: 8.99,
    calories: 599,
    category: "burgers",
    image: "burger2.webp",
  },

  // {
  //   id: "m3",
  //   name: "Egg Burger",
  //   description: "Fried egg and bacon",
  //   price: 6.99,
  //   calories: 599,
  //   category: "burgers",
  //   image: "burger3.webp",
  // },
  // {
  //   id: "m4",
  //   name: "Fries",
  //   description: "Handcut fresh every day!",
  //   price: 3.99,
  //   calories: 400,
  //   category: "fries",
  //   image: "fries1.webp",
  // },
  // {
  //   id: "m5",
  //   name: "Sweet Potato Fries",
  //   description: "Handcut fresh every day. Served with cinnamon butter.",
  //   price: 3.99,
  //   calories: 300,
  //   category: "fries",
  //   image: "fries2.webp",
  // },
  // {
  //   id: "m6",
  //   name: "Fountain Drink",
  //   description: "soda",
  //   price: 1.99,
  //   calories: 250,
  //   category: "drinks",
  //   image: "soda1.webp",
  // },

  // {
  //   id: "m7",
  //   name: "Classic Burger",
  //   description: "Our classic burger",
  //   price: 1.99,
  //   calories: 250,
  //   category: "burgers",
  //   image: "/burger4.webp",
  // },
];
